version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - checkout
      - run: make build
      - run: make test

  publish-latest:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "${QUAY_PASSWORD}" | docker login -u "${QUAY_USERNAME}" --password-stdin quay.io
      - run: make docker-publish
      - run: DOCKER_TAG=latest make docker-publish

  release:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "${QUAY_PASSWORD}" | docker login -u "${QUAY_USERNAME}" --password-stdin quay.io
      - run: DOCKER_TAG=$CIRCLE_TAG make docker-publish

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - publish-latest:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - release:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
